### ISSUE TITLE
Add documentation lots of exported Diff functions

### ISSUE THREAD

**Issue by aperrot42** [mcluseau/go-diff#2]
Hello super @mcluseau we're using this lib at isi.nc quite intensively. Looking quickly at diff.go, if you've got 5 minutes to explain the difference between :

```
func Diff(referenceValues, currentValues <-chan KeyValue, changes chan Change, cancel <-chan bool) error

func DiffStreamReference(referenceValues, currentValues <-chan KeyValue, changes chan Change, cancel <-chan bool) error

func DiffStreamIndex(referenceValues <-chan KeyValue, currentIndex Index, changes chan Change, cancel <-chan bool) error

func DiffIndexStream(referenceIndex Index, currentValues <-chan KeyValue, changes chan Change, cancel <-chan bool) error

func DiffIndexIndex(referenceIndex Index, currentIndex Index, changes chan Change, cancel <-chan bool) error
```

is it just basically if the reference/index comes from a kafka topic or from a go channel ?

**Comment by mcluseau** [comment]
I'm not sure about what's unclear in the godoc (outside a typo "less faster" instead of "faster"); also the code of each "wrapper" is very short. Basically, if one doesn't want to think at all, it's for Diff; assuming more constraints allows the use of optimized implementations.
